 name: Python Lint Checker
 
 on:
   push:
     branches: [release*, main]
 
 jobs:
   action-check:
     name: Check
     runs-on: ubuntu-18.04
     strategy:
       max-parallel: 10
     steps:
       - run: |
           echo ${{ github.event.pull_request.number }}
           if [ ${{ github.ref }} == "refs/heads/main" ]; then
             echo "main branch"
             echo "SERVER_STAGE=NEXTWEEK" >> $GITHUB_ENV
           else 
             echo "release branch"
           fi
       - name: test
         run: |
           echo "$SERVER_STAGE"
